import { useState, useMemo } from "react";
import { Ticket } from "@shared/schema";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Search, Clock, User, Building2, ChevronRight, CalendarClock, X } from "lucide-react";

function isAutoGeneratedEntry(text: string): boolean {
  return (
    text.includes("(Auto-Generated)") ||
    text.startsWith("⚠") ||
    text.startsWith("Slack notification sent")
  );
}

function timeSinceUpdate(ticket: Ticket): string {
  const candidates: number[] = [];
  if (ticket.createdAt) candidates.push(new Date(ticket.createdAt).getTime());
  if (ticket.nextStepsHistory?.length) {
    for (const entry of ticket.nextStepsHistory) {
      if (entry.updatedAt && !isAutoGeneratedEntry(entry.text || "")) {
        candidates.push(new Date(entry.updatedAt).getTime());
      }
    }
  }
  if (candidates.length === 0) return "";
  const diffMs = Date.now() - Math.max(...candidates);
  const hours = Math.floor(diffMs / (1000 * 60 * 60));
  if (hours < 1) return "<1h";
  if (hours < 24) return `${hours}h`;
  const days = Math.floor(hours / 24);
  return `${days}d`;
}

function getPriorityLevel(label: string | null | undefined): number {
  if (!label) return 4;
  const m = label.match(/\bP(\d+)\b/i);
  return m ? parseInt(m[1]) : 4;
}

function getPriorityBorderClass(label: string | null | undefined): string {
  switch (getPriorityLevel(label)) {
    case 1: return "border-l-red-500";
    case 2: return "border-l-orange-400";
    case 3: return "border-l-amber-400";
    default: return "border-l-blue-400";
  }
}

function getPriorityBadgeClass(label: string | null | undefined): string {
  switch (getPriorityLevel(label)) {
    case 1: return "bg-red-500/15 text-red-500 border-red-500/20";
    case 2: return "bg-orange-400/15 text-orange-400 border-orange-400/20";
    case 3: return "bg-amber-400/15 text-amber-500 border-amber-400/20";
    default: return "bg-blue-400/15 text-blue-400 border-blue-400/20";
  }
}

function shortenPriorityLabel(label: string | null | undefined): string {
  if (!label) return "—";
  const parts = label.split(":");
  if (parts.length >= 2) return parts.slice(0, 2).map(s => s.trim()).join(": ");
  return label;
}

function formatNextUpdate(dateStr: string | null | undefined): string {
  if (!dateStr) return "";
  const d = new Date(dateStr);
  const now = new Date();
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());
  const target = new Date(d.getFullYear(), d.getMonth(), d.getDate());
  const diffDays = Math.round((target.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
  if (diffDays < 0) return `${Math.abs(diffDays)}d overdue`;
  if (diffDays === 0) return "Today";
  if (diffDays === 1) return "Tomorrow";
  return `in ${diffDays}d`;
}

function isOverdue(dateStr: string | null | undefined): boolean {
  if (!dateStr) return false;
  const d = new Date(dateStr);
  const today = new Date();
  today.setHours(0, 0, 0, 0);
  return d < today;
}

interface MobileTicketCardProps {
  ticket: Ticket;
  onEdit: (ticket: Ticket) => void;
}

function MobileTicketCard({ ticket, onEdit }: MobileTicketCardProps) {
  const since = timeSinceUpdate(ticket);
  const nextUpdateRaw = ticket.estimatedNextUpdate;
  const nextUpdate = nextUpdateRaw instanceof Date ? nextUpdateRaw.toISOString() : nextUpdateRaw;
  const overdue = isOverdue(nextUpdate);
  const borderClass = getPriorityBorderClass(ticket.priorityLabel);
  const badgeClass = getPriorityBadgeClass(ticket.priorityLabel);
  const priorityShort = shortenPriorityLabel(ticket.priorityLabel);

  return (
    <button
      className={`w-full text-left bg-card border border-border rounded-xl p-4 pl-5 border-l-4 ${borderClass} shadow-sm active:scale-[0.98] transition-transform`}
      data-testid={`card-mobile-ticket-${ticket.id}`}
      onClick={() => onEdit(ticket)}
    >
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-2 flex-wrap min-w-0">
          <span className="text-xs font-semibold text-muted-foreground shrink-0">
            {ticket.ticketNumber || `#${ticket.id}`}
          </span>
          <span className={`text-xs px-2 py-0.5 rounded-full border font-medium ${badgeClass}`}>
            {priorityShort}
          </span>
          {ticket.status === "open" ? (
            <span className="text-xs px-2 py-0.5 rounded-full bg-green-500/15 text-green-600 dark:text-green-400 border border-green-500/20 font-medium">
              Open
            </span>
          ) : (
            <span className="text-xs px-2 py-0.5 rounded-full bg-muted text-muted-foreground border border-border font-medium">
              Closed
            </span>
          )}
        </div>
        <ChevronRight className="h-4 w-4 text-muted-foreground shrink-0 mt-0.5" />
      </div>

      <p className="mt-2 text-sm font-medium text-foreground leading-snug line-clamp-2">
        {ticket.title || "Untitled"}
      </p>

      <div className="mt-3 flex flex-col gap-1.5">
        {ticket.customerName && (
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <Building2 className="h-3 w-3 shrink-0" />
            <span className="truncate">{ticket.customerName}</span>
            {ticket.systemId && (
              <>
                <span className="text-border">·</span>
                <span className="font-mono text-xs shrink-0">{ticket.systemId}</span>
              </>
            )}
          </div>
        )}
        <div className="flex items-center justify-between gap-2">
          <div className="flex items-center gap-1.5 text-xs text-muted-foreground min-w-0">
            <User className="h-3 w-3 shrink-0" />
            <span className="truncate">{ticket.assigneeName || "Unassigned"}</span>
          </div>
          <div className="flex items-center gap-2 shrink-0">
            {nextUpdate && (
              <div className={`flex items-center gap-1 text-xs ${overdue ? "text-red-500 font-medium" : "text-muted-foreground"}`}>
                <CalendarClock className="h-3 w-3" />
                <span>{formatNextUpdate(nextUpdate)}</span>
              </div>
            )}
            {since && (
              <div className="flex items-center gap-1 text-xs text-muted-foreground">
                <Clock className="h-3 w-3" />
                <span>{since}</span>
              </div>
            )}
          </div>
        </div>
      </div>

      {ticket.nextSteps && (
        <p className="mt-2 text-xs text-muted-foreground line-clamp-1 italic border-t border-border/50 pt-2">
          {ticket.nextSteps}
        </p>
      )}
    </button>
  );
}

interface MobileTicketListProps {
  tickets: Ticket[];
  onEdit: (ticket: Ticket) => void;
}

export function MobileTicketList({ tickets, onEdit }: MobileTicketListProps) {
  const [search, setSearch] = useState("");
  const [openOnly, setOpenOnly] = useState(true);

  const displayed = useMemo(() => {
    let list = tickets;
    if (openOnly) list = list.filter(t => t.status === "open");
    if (search.trim()) {
      const q = search.trim().toLowerCase();
      list = list.filter(t =>
        (t.ticketNumber || "").toLowerCase().includes(q) ||
        (t.title || "").toLowerCase().includes(q) ||
        (t.customerName || "").toLowerCase().includes(q) ||
        (t.assigneeName || "").toLowerCase().includes(q) ||
        (t.systemId || "").toLowerCase().includes(q)
      );
    }
    return list;
  }, [tickets, search, openOnly]);

  return (
    <div className="space-y-3">
      <div className="flex gap-2">
        <div className="relative flex-1">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
          <Input
            data-testid="input-mobile-search"
            className="pl-9 pr-9 h-10 bg-background"
            placeholder="Search tickets…"
            value={search}
            onChange={e => setSearch(e.target.value)}
          />
          {search && (
            <button
              className="absolute right-3 top-1/2 -translate-y-1/2 text-muted-foreground hover:text-foreground"
              onClick={() => setSearch("")}
            >
              <X className="h-4 w-4" />
            </button>
          )}
        </div>
        <Button
          data-testid="button-mobile-open-toggle"
          variant={openOnly ? "default" : "outline"}
          size="sm"
          className="h-10 px-3 shrink-0 text-xs font-medium"
          onClick={() => setOpenOnly(v => !v)}
        >
          Open only
        </Button>
      </div>

      <p className="text-xs text-muted-foreground px-1">
        {displayed.length} {displayed.length === 1 ? "ticket" : "tickets"}
      </p>

      {displayed.length === 0 ? (
        <div className="text-center py-12 text-muted-foreground text-sm">
          No tickets match your filters.
        </div>
      ) : (
        <div className="space-y-2 pb-6">
          {displayed.map(ticket => (
            <MobileTicketCard key={ticket.id} ticket={ticket} onEdit={onEdit} />
          ))}
        </div>
      )}
    </div>
  );
}
