import { useState, useMemo, useEffect, Component } from "react";
import type { ReactNode, ErrorInfo } from "react";
import { Ticket } from "@shared/schema";
import {
  Table,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
  TableBody,
} from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { Database, ArrowUp, ArrowDown, Filter, Check, Building2, Copy, CopyCheck, Flag, Sparkles, Package } from "lucide-react";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Popover,
  PopoverContent,
  PopoverTrigger,
} from "@/components/ui/popover";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { TicketForm } from "./ticket-form";
import { Input } from "./ui/input";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { apiRequest } from "@/lib/queryClient";
import { useAuth } from "@/hooks/use-auth";

function splitNameParts(name: string): string[] {
  const trimmed = name.trim();
  if (trimmed.includes(" ")) return trimmed.split(/\s+/);
  if (trimmed.includes("@")) {
    // Extract the local part of an email and treat dot/underscore as word separators
    const local = trimmed.split("@")[0];
    const parts = local.split(/[._-]+/).filter(Boolean).map(p => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase());
    return parts.length > 0 ? parts : [local];
  }
  const camel = trimmed.replace(/([a-z\u00e0-\u00ff])([A-Z\u00c0-\u00df])/g, "$1 $2");
  if (camel !== trimmed) return camel.split(" ");
  return [trimmed];
}

function buildShortNameMap(names: string[]): Map<string, string> {
  const normalize = (name: string) => splitNameParts(name).join(" ");
  const unique = Array.from(new Set(names.filter(Boolean)));

  // Group all variants of the same person under one canonical form
  const canonicalToOriginals = new Map<string, string[]>();
  for (const name of unique) {
    const canonical = normalize(name);
    const group = canonicalToOriginals.get(canonical) ?? [];
    group.push(name);
    canonicalToOriginals.set(canonical, group);
  }

  // Count first names using deduplicated canonicals only
  const firstNameCount = new Map<string, number>();
  for (const canonical of canonicalToOriginals.keys()) {
    const first = canonical.split(" ")[0];
    if (first) firstNameCount.set(first, (firstNameCount.get(first) ?? 0) + 1);
  }

  // Map every variant to its short form
  const map = new Map<string, string>();
  for (const [canonical, originals] of canonicalToOriginals) {
    const parts = canonical.split(" ");
    const first = parts[0];
    let shortForm = first;
    if (!first) {
      shortForm = canonical;
    } else if ((firstNameCount.get(first) ?? 0) > 1) {
      const lastInitial = parts[1]?.[0]?.toUpperCase();
      shortForm = lastInitial ? `${first} ${lastInitial}` : first;
    }
    for (const orig of originals) map.set(orig, shortForm);
  }
  return map;
}

function getTicketCreator(ticket: { nextStepsHistory?: Array<{ text: string; updatedBy: string; updatedAt: string }> | null }): string | null {
  const history = ticket.nextStepsHistory;
  if (!history?.length) return null;
  const SYSTEM_NAMES = new Set(["External", "System", "Unknown", "Airtable Sync"]);
  const isHuman = (name: string) => !!name && !SYSTEM_NAMES.has(name);
  const created = history.find(e => e.text === "Ticket created");
  if (created?.updatedBy && isHuman(created.updatedBy)) return created.updatedBy;
  const first = history.find(e => isHuman(e.updatedBy));
  return first?.updatedBy ?? null;
}

interface TicketOptions {
  priorityLabels: string[];
  customers: string[];
  assignees: string[];
  systemIds: string[];
  regions: string[];
  customerSystemIds: Record<string, string[]>;
  customerContacts: Record<string, { name: string; email: string | null; phone: string | null }[]>;
}

function priorityLevelFromLabel(label: string): string {
  const m = label.match(/P(\d+)/i);
  if (!m) return "medium";
  const level = parseInt(m[1]);
  if (level === 1) return "high";
  if (level === 2) return "medium";
  return "low";
}

function shortenPriority(label: string): string {
  const parts = label.split(":");
  if (parts.length >= 2) {
    return parts.slice(0, 2).map(s => s.trim()).join(": ");
  }
  return label;
}

function isAutoGeneratedEntry(text: string): boolean {
  return (
    text.includes("(Auto-Generated)") ||
    text.startsWith("⚠") ||
    text.startsWith("Slack notification sent")
  );
}

function timeSinceUpdate(ticket: Ticket): string {
  // Use the most recent of: createdAt or any *real user* nextStepsHistory entry.
  // Intentionally excludes ticket.updatedAt (bumped by background sync) and
  // auto-generated entries like daily review propagation and Airtable errors.
  const candidates: number[] = [];
  if (ticket.createdAt) candidates.push(new Date(ticket.createdAt).getTime());
  if (ticket.nextStepsHistory?.length) {
    for (const entry of ticket.nextStepsHistory) {
      if (entry.updatedAt && !isAutoGeneratedEntry(entry.text || "")) {
        candidates.push(new Date(entry.updatedAt).getTime());
      }
    }
  }
  if (candidates.length === 0) return "";
  const diffMs = Date.now() - Math.max(...candidates);
  const hours = Math.floor(diffMs / (1000 * 60 * 60));
  if (hours < 1) return "<1H";
  if (hours < 24) return `${hours}H`;
  const days = Math.floor(hours / 24);
  return `${days}D`;
}

function hoursOpen(ticket: Ticket): string {
  const start = ticket.submittedAt || ticket.createdAt;
  if (!start) return "—";
  const startDate = new Date(start);

  let endDate: Date;
  if (ticket.status === "closed" && ticket.resolvedAt) {
    endDate = new Date(ticket.resolvedAt);
  } else if (ticket.status === "closed" && ticket.updatedAt) {
    endDate = new Date(ticket.updatedAt);
  } else {
    endDate = new Date();
  }

  const diffMs = endDate.getTime() - startDate.getTime();
  const hours = Math.round(diffMs / (1000 * 60 * 60));
  if (hours < 1) return "<1h";
  if (hours >= 24) {
    const days = Math.floor(hours / 24);
    const rem = hours % 24;
    return rem > 0 ? `${days}d ${rem}h` : `${days}d`;
  }
  return `${hours}h`;
}

type SortColumn = "isrNumber" | "title" | "customer" | "systemId" | "priority" | "hours" | "assignee" | null;
type SortDirection = "asc" | "desc";

function getSortValue(ticket: Ticket, column: SortColumn): string | number | Date {
  switch (column) {
    case "isrNumber":
      return ticket.ticketNumber || `#${ticket.id}`;
    case "title":
      return ticket.title || "";
    case "customer":
      return ticket.customerName || "";
    case "systemId":
      return ticket.systemId || "";
    case "priority": {
      const match = ticket.priorityLabel?.match(/P(\d+)/i);
      const level = match ? parseInt(match[1]) : 999;
      const subMatch = ticket.priorityLabel?.match(/P\d+-(\d+)/i);
      const sub = subMatch ? parseInt(subMatch[1]) : 0;
      return level * 10 + sub;
    }
    case "hours": {
      const start = ticket.submittedAt || ticket.createdAt;
      if (!start) return 0;
      const startDate = new Date(start);
      let endDate: Date;
      if (ticket.status === "closed" && ticket.resolvedAt) {
        endDate = new Date(ticket.resolvedAt);
      } else if (ticket.status === "closed" && ticket.updatedAt) {
        endDate = new Date(ticket.updatedAt);
      } else {
        endDate = new Date();
      }
      return endDate.getTime() - startDate.getTime();
    }
    case "assignee":
      return ticket.assigneeName || "";
    default:
      return "";
  }
}

function SortableHeader({
  column,
  label,
  currentColumn,
  sortDirection,
  onSort,
  filterOptions,
  selectedValues,
  onToggle,
  onClear,
  extraContent,
}: {
  column: SortColumn;
  label: string;
  currentColumn: SortColumn;
  sortDirection: SortDirection;
  onSort: (col: SortColumn) => void;
  filterOptions?: string[];
  selectedValues?: Set<string>;
  onToggle?: (value: string) => void;
  onClear?: () => void;
  extraContent?: React.ReactNode;
}) {
  const [search, setSearch] = useState("");
  const isActive = currentColumn === column;
  const isFilterable = !!filterOptions;
  const hasFilter = (selectedValues?.size ?? 0) > 0;

  const filtered = filterOptions
    ? filterOptions.filter(o => o.toLowerCase().includes(search.toLowerCase()))
    : [];

  return (
    <TableHead className="text-[#F0F5F1]/70 select-none p-0">
      <div className="flex items-center gap-1 px-4 py-3">
        <span
          className="cursor-pointer hover:text-[#F0F5F1]/90 transition-colors flex items-center gap-1"
          onClick={() => onSort(column)}
        >
          {label}
          {isActive && (
            sortDirection === "asc"
              ? <ArrowUp className="h-3 w-3" />
              : <ArrowDown className="h-3 w-3" />
          )}
        </span>
        {isFilterable && (
          <Popover onOpenChange={(open) => { if (!open) setSearch(""); }}>
            <PopoverTrigger asChild>
              <button
                className={`ml-1 p-1 rounded hover:bg-white/10 transition-colors ${hasFilter ? "text-[#FF9100]" : "text-[#F0F5F1]/40 hover:text-[#F0F5F1]/70"}`}
                onClick={(e) => e.stopPropagation()}
                data-testid={`filter-${column}`}
              >
                <Filter className="h-3.5 w-3.5" />
              </button>
            </PopoverTrigger>
            <PopoverContent className="w-72 p-3" align="start">
              <div className="flex items-center justify-between mb-2">
                <p className="text-sm font-semibold">Filter by {label}</p>
                {hasFilter && (
                  <button
                    onClick={onClear}
                    className="text-xs text-muted-foreground hover:text-foreground"
                  >
                    Clear
                  </button>
                )}
              </div>
              <Input
                placeholder="Search..."
                className="h-8 text-sm mb-2"
                value={search}
                onChange={(e) => setSearch(e.target.value)}
              />
              <div className="space-y-0.5 max-h-64 overflow-y-auto">
                {filtered.map((option) => (
                  <button
                    key={option}
                    onClick={() => onToggle?.(option)}
                    className="w-full flex items-center gap-2 px-2 py-1.5 rounded hover:bg-accent text-sm text-left"
                  >
                    <div className={`h-4 w-4 rounded border flex-shrink-0 flex items-center justify-center ${selectedValues?.has(option) ? "bg-primary border-primary" : "border-input"}`}>
                      {selectedValues?.has(option) && <Check className="h-3 w-3 text-primary-foreground" />}
                    </div>
                    <span className="truncate">{option}</span>
                  </button>
                ))}
                {filtered.length === 0 && (
                  <p className="text-xs text-muted-foreground text-center py-2">No options</p>
                )}
              </div>
            </PopoverContent>
          </Popover>
        )}
        {extraContent}
      </div>
    </TableHead>
  );
}

// ── Error Boundary for ticket edit dialog ─────────────────────────────────────
class TicketFormErrorBoundary extends Component<{ children: ReactNode }, { error: Error | null }> {
  constructor(props: { children: ReactNode }) {
    super(props);
    this.state = { error: null };
  }
  static getDerivedStateFromError(error: Error) {
    return { error };
  }
  componentDidCatch(error: Error, info: ErrorInfo) {
    console.error("[TicketForm crash]", error, info);
  }
  render() {
    if (this.state.error) {
      return (
        <div className="p-6 space-y-3">
          <p className="text-sm font-medium text-destructive">Failed to load ticket form</p>
          <p className="text-xs text-muted-foreground font-mono break-all">{this.state.error.message}</p>
          <button
            onClick={() => this.setState({ error: null })}
            className="text-xs underline text-muted-foreground hover:text-foreground"
          >
            Try again
          </button>
        </div>
      );
    }
    return this.props.children;
  }
}

// ── Customer Directory Dialog ─────────────────────────────────────────────────
function CustomerDirectoryDialog({
  open,
  onOpenChange,
  customerContacts,
}: {
  open: boolean;
  onOpenChange: (v: boolean) => void;
  customerContacts: Record<string, { name: string; email: string | null; phone: string | null }[]>;
}) {
  const [search, setSearch] = useState("");
  const [copied, setCopied] = useState(false);

  const entries = useMemo(() => {
    const q = search.toLowerCase().trim();
    return Object.entries(customerContacts)
      .filter(([customer, contacts]) => {
        if (!q) return true;
        if (customer.toLowerCase().includes(q)) return true;
        return contacts.some(c =>
          c.name.toLowerCase().includes(q) ||
          (c.email ?? "").toLowerCase().includes(q) ||
          (c.phone ?? "").toLowerCase().includes(q)
        );
      })
      .sort(([a], [b]) => a.localeCompare(b));
  }, [customerContacts, search]);

  const handleCopyAll = () => {
    const lines: string[] = [];
    entries.forEach(([customer, contacts]) => {
      lines.push(customer);
      contacts.forEach(c => {
        const parts = [c.name, c.email, c.phone].filter(Boolean);
        lines.push(`  ${parts.join(" | ")}`);
      });
    });
    navigator.clipboard.writeText(lines.join("\n")).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-[540px] max-h-[80vh] flex flex-col">
        <DialogHeader>
          <div className="flex items-center justify-between gap-3 pr-6">
            <DialogTitle className="flex items-center gap-2">
              <Building2 className="h-4 w-4 text-[#FF9100]" />
              Customer Directory
            </DialogTitle>
            <Button
              size="sm"
              variant="outline"
              className="h-7 text-xs gap-1.5 shrink-0"
              onClick={handleCopyAll}
              data-testid="btn-copy-directory"
            >
              {copied ? <CopyCheck className="h-3.5 w-3.5 text-green-500" /> : <Copy className="h-3.5 w-3.5" />}
              {copied ? "Copied!" : "Copy all"}
            </Button>
          </div>
        </DialogHeader>

        <div className="px-1 pt-1 pb-2">
          <Input
            placeholder="Search customers, contacts, email, or phone…"
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="h-8 text-sm"
            data-testid="input-directory-search"
            autoFocus
          />
        </div>

        <div className="flex-1 overflow-y-auto pr-1 space-y-1 min-h-0">
          {entries.length === 0 && (
            <p className="text-sm text-muted-foreground text-center py-8">No matches found.</p>
          )}
          {entries.map(([customer, contacts]) => (
            <div key={customer} className="rounded-lg border border-border/50 bg-muted/20 px-3 py-2.5">
              <p
                className="text-sm font-semibold text-foreground select-text cursor-text mb-1.5"
                data-testid={`directory-customer-${customer}`}
              >
                {customer}
              </p>
              {contacts.length > 0 ? (
                <div className="space-y-1">
                  {contacts.map((c, i) => (
                    <div key={i} className="flex flex-col gap-0.5 pl-2 border-l-2 border-[#FF9100]/30">
                      <span className="text-xs font-medium text-foreground/90 select-text cursor-text">
                        {c.name}
                      </span>
                      {c.email && (
                        <span className="text-xs text-muted-foreground select-text cursor-text">
                          {c.email}
                        </span>
                      )}
                      {c.phone && (
                        <span className="text-xs text-muted-foreground select-text cursor-text">
                          {c.phone}
                        </span>
                      )}
                    </div>
                  ))}
                </div>
              ) : (
                <p className="text-xs text-muted-foreground/50">No contacts on record</p>
              )}
            </div>
          ))}
        </div>

        <div className="pt-2 border-t border-border/40 text-xs text-muted-foreground">
          {entries.length} customer{entries.length !== 1 ? "s" : ""}
          {search && ` matching "${search}"`}
        </div>
      </DialogContent>
    </Dialog>
  );
}

export interface ColumnFilters {
  customer: string[];
  priority: string[];
  assignee: string[];
}

export function TicketTable({
  tickets,
  editingTicket: externalEditing,
  onEditingChange,
  onFilteredCountChange,
  initialColumnFilters,
  onColumnFiltersChange,
}: {
  tickets: Ticket[];
  editingTicket?: Ticket | null;
  onEditingChange?: (t: Ticket | null) => void;
  onFilteredCountChange?: (count: number) => void;
  initialColumnFilters?: ColumnFilters;
  onColumnFiltersChange?: (f: ColumnFilters) => void;
}) {
  const [internalEditing, setInternalEditing] = useState<Ticket | null>(null);
  const [copiedLink, setCopiedLink] = useState(false);
  const editingTicket = externalEditing !== undefined ? externalEditing : internalEditing;
  const setEditingTicket = (t: Ticket | null) => {
    setInternalEditing(t);
    onEditingChange?.(t);
  };
  const [sortColumn, setSortColumn] = useState<SortColumn>(null);
  const [sortDirection, setSortDirection] = useState<SortDirection>("asc");
  const [customerFilter, setCustomerFilter] = useState<Set<string>>(
    () => new Set(initialColumnFilters?.customer ?? [])
  );
  const [priorityFilter, setPriorityFilter] = useState<Set<string>>(
    () => new Set(initialColumnFilters?.priority ?? [])
  );
  const [assigneeFilter, setAssigneeFilter] = useState<Set<string>>(
    () => new Set(initialColumnFilters?.assignee ?? [])
  );
  const [changingPriority, setChangingPriority] = useState<Set<number>>(new Set());
  const [togglingSupport, setTogglingSupport] = useState<Set<number>>(new Set());
  const [togglingParts, setTogglingParts] = useState<Set<number>>(new Set());
  const [directoryOpen, setDirectoryOpen] = useState(false);

  const { data: options } = useQuery<TicketOptions>({ queryKey: ["/api/tickets/options"] });
  const queryClient = useQueryClient();
  const { user } = useAuth();
  const loggedInUserName = useMemo(() => {
    if (!user) return "Unknown";
    return [user.firstName, user.lastName].filter(Boolean).join(" ") || "Unknown";
  }, [user]);

  const { data: slackMembers = [] } = useQuery<Array<{ name: string; id: string }>>({
    queryKey: ["/api/slack/members"],
    staleTime: 10 * 60 * 1000,
  });

  const shortNameMap = useMemo(() => {
    const names: string[] = slackMembers.map(m => m.name).filter(Boolean);
    for (const t of tickets) {
      if (t.assigneeName) names.push(t.assigneeName);
      const creator = getTicketCreator(t);
      if (creator) names.push(creator);
    }
    return buildShortNameMap(names);
  }, [tickets, slackMembers]);

  const sn = (name: string | null | undefined): string =>
    name ? (shortNameMap.get(name) ?? splitNameParts(name)[0] ?? name) : "—";

  const isNewTicket = (ticket: Ticket) => {
    if (!ticket.createdAt) return false;
    const age = Date.now() - new Date(ticket.createdAt).getTime();
    return age < 48 * 60 * 60 * 1000;
  };

  const toggleNeedsSupport = async (ticket: Ticket) => {
    if (togglingSupport.has(ticket.id)) return;
    setTogglingSupport(prev => new Set(prev).add(ticket.id));
    try {
      await apiRequest("PATCH", `/api/tickets/${ticket.id}`, { needsSupport: !ticket.needsSupport });
      await queryClient.invalidateQueries({ queryKey: ["/api/tickets"] });
    } finally {
      setTogglingSupport(prev => { const next = new Set(prev); next.delete(ticket.id); return next; });
    }
  };

  const togglePartsNeeded = async (ticket: Ticket) => {
    if (togglingParts.has(ticket.id)) return;
    setTogglingParts(prev => new Set(prev).add(ticket.id));
    try {
      await apiRequest("PATCH", `/api/tickets/${ticket.id}`, { partsNeeded: !ticket.partsNeeded });
      await queryClient.invalidateQueries({ queryKey: ["/api/tickets"] });
    } finally {
      setTogglingParts(prev => { const next = new Set(prev); next.delete(ticket.id); return next; });
    }
  };

  const handlePriorityChange = async (ticket: Ticket, newLabel: string | null) => {
    if (changingPriority.has(ticket.id)) return;
    const fromLabel = ticket.priorityLabel;
    if (fromLabel === newLabel) return;

    setChangingPriority(prev => new Set(prev).add(ticket.id));
    try {
      const historyEntry = {
        text: newLabel
          ? (fromLabel
              ? `Priority changed from "${fromLabel}" to "${newLabel}"`
              : `Priority set to "${newLabel}"`)
          : `Priority cleared (was "${fromLabel}")`,
        updatedBy: loggedInUserName,
        updatedAt: new Date().toISOString(),
      };
      const currentHistory = ticket.nextStepsHistory || [];
      await apiRequest("PATCH", `/api/tickets/${ticket.id}`, {
        priorityLabel: newLabel || null,
        priority: newLabel ? priorityLevelFromLabel(newLabel) : "medium",
        nextStepsHistory: [...currentHistory, historyEntry],
      });
      await queryClient.invalidateQueries({ queryKey: ["/api/tickets"] });
    } finally {
      setChangingPriority(prev => {
        const next = new Set(prev);
        next.delete(ticket.id);
        return next;
      });
    }
  };

  const handleSort = (column: SortColumn) => {
    if (sortColumn === column) {
      setSortDirection(sortDirection === "asc" ? "desc" : "asc");
    } else {
      setSortColumn(column);
      setSortDirection("asc");
    }
  };

  const makeToggle = (col: "customer" | "priority" | "assignee", current: Set<string>, setter: (s: Set<string>) => void) =>
    (value: string) => {
      const next = new Set(current);
      next.has(value) ? next.delete(value) : next.add(value);
      setter(next);
      if (onColumnFiltersChange) {
        onColumnFiltersChange({
          customer: col === "customer" ? [...next] : [...customerFilter],
          priority: col === "priority" ? [...next] : [...priorityFilter],
          assignee: col === "assignee" ? [...next] : [...assigneeFilter],
        });
      }
    };

  const makeClear = (col: "customer" | "priority" | "assignee", setter: (s: Set<string>) => void) =>
    () => {
      setter(new Set());
      if (onColumnFiltersChange) {
        onColumnFiltersChange({
          customer: col === "customer" ? [] : [...customerFilter],
          priority: col === "priority" ? [] : [...priorityFilter],
          assignee: col === "assignee" ? [] : [...assigneeFilter],
        });
      }
    };

  const getOptions = (col: "customer" | "priority" | "assignee"): string[] => {
    const set = new Set<string>();
    tickets.forEach((t) => {
      const val =
        col === "customer" ? t.customerName :
        col === "priority" ? (t.priorityLabel ? shortenPriority(t.priorityLabel) : null) :
        t.assigneeName;
      if (val) set.add(val);
    });
    if (col === "priority") {
      return Array.from(set).sort((a, b) => {
        const aPrefix = a.match(/^([^:]+):/)?.[1].trim() ?? "";
        const bPrefix = b.match(/^([^:]+):/)?.[1].trim() ?? "";
        const aIsFO = aPrefix === "FO";
        const bIsFO = bPrefix === "FO";
        if (aIsFO && !bIsFO) return -1;
        if (!aIsFO && bIsFO) return 1;
        const aPLevel = parseInt(a.match(/P(\d+)/i)?.[1] ?? "99");
        const bPLevel = parseInt(b.match(/P(\d+)/i)?.[1] ?? "99");
        if (aPLevel !== bPLevel) return aPLevel - bPLevel;
        return a.localeCompare(b);
      });
    }
    return Array.from(set).sort();
  };

  const filteredAndSortedTickets = tickets.filter((t) => {
    if (customerFilter.size > 0 && !customerFilter.has(t.customerName || "")) return false;
    if (priorityFilter.size > 0 && !priorityFilter.has(t.priorityLabel ? shortenPriority(t.priorityLabel) : "")) return false;
    if (assigneeFilter.size > 0) {
      const tNameNorm = (t.assigneeName || "").toLowerCase().trim();
      const matches = tNameNorm && [...assigneeFilter].some(f => f.toLowerCase().trim() === tNameNorm);
      if (!matches) return false;
    }
    return true;
  }).sort((a, b) => {
    if (!sortColumn) return 0;

    const aVal = getSortValue(a, sortColumn);
    const bVal = getSortValue(b, sortColumn);

    let comparison = 0;
    if (typeof aVal === "string" && typeof bVal === "string") {
      comparison = aVal.localeCompare(bVal);
    } else if (typeof aVal === "number" && typeof bVal === "number") {
      comparison = aVal - bVal;
    } else {
      comparison = String(aVal).localeCompare(String(bVal));
    }

    return sortDirection === "asc" ? comparison : -comparison;
  });

  useEffect(() => {
    onFilteredCountChange?.(filteredAndSortedTickets.length);
  }, [filteredAndSortedTickets.length, onFilteredCountChange]);

  if (tickets.length === 0) {
    return (
      <div className="flex flex-col items-center justify-center py-24 text-center border rounded-xl border-dashed border-border/60 bg-muted/20">
        <div className="h-12 w-12 rounded-full bg-muted flex items-center justify-center mb-4">
          <Database className="h-5 w-5 text-muted-foreground" />
        </div>
        <h3 data-testid="text-empty-state" className="text-lg font-medium text-foreground">No tickets found</h3>
        <p className="text-sm text-muted-foreground mt-1 max-w-sm">
          No tickets match your current filters.
        </p>
      </div>
    );
  }

  return (
    <>
      <div className="rounded-xl border bg-card overflow-hidden shadow-sm shadow-black/5">
        <div className="overflow-x-auto">
        <Table>
          <TableHeader className="bg-[#163439]">
            <TableRow className="hover:bg-transparent border-b border-white/10">
              <SortableHeader column="isrNumber" label="ISR #" currentColumn={sortColumn} sortDirection={sortDirection} onSort={handleSort} />
              <TableHead className="w-7 px-1 text-center" />
              <SortableHeader column="title" label="Title" currentColumn={sortColumn} sortDirection={sortDirection} onSort={handleSort} />
              <SortableHeader
                column="customer" label="Customer"
                currentColumn={sortColumn} sortDirection={sortDirection} onSort={handleSort}
                filterOptions={getOptions("customer")}
                selectedValues={customerFilter}
                onToggle={makeToggle("customer", customerFilter, setCustomerFilter)}
                onClear={makeClear("customer", setCustomerFilter)}
                extraContent={
                  <button
                    className="ml-0.5 p-1 rounded hover:bg-white/10 transition-colors text-[#F0F5F1]/40 hover:text-[#F0F5F1]/70"
                    onClick={(e) => { e.stopPropagation(); setDirectoryOpen(true); }}
                    data-testid="btn-customer-directory"
                    title="Customer Directory"
                  >
                    <Building2 className="h-3.5 w-3.5" />
                  </button>
                }
              />
              <SortableHeader column="systemId" label="System ID" currentColumn={sortColumn} sortDirection={sortDirection} onSort={handleSort} />
              <SortableHeader
                column="priority" label="Priority"
                currentColumn={sortColumn} sortDirection={sortDirection} onSort={handleSort}
                filterOptions={getOptions("priority")}
                selectedValues={priorityFilter}
                onToggle={makeToggle("priority", priorityFilter, setPriorityFilter)}
                onClear={makeClear("priority", setPriorityFilter)}
              />
              <SortableHeader column="hours" label="Age" currentColumn={sortColumn} sortDirection={sortDirection} onSort={handleSort} />
              <SortableHeader
                column="assignee" label="Assignee"
                currentColumn={sortColumn} sortDirection={sortDirection} onSort={handleSort}
                filterOptions={getOptions("assignee")}
                selectedValues={assigneeFilter}
                onToggle={makeToggle("assignee", assigneeFilter, setAssigneeFilter)}
                onClear={makeClear("assignee", setAssigneeFilter)}
              />
            </TableRow>
          </TableHeader>
          <TableBody>
            {filteredAndSortedTickets.map((ticket) => (
              <TableRow key={ticket.id} data-testid={`row-ticket-${ticket.id}`} className="group transition-colors">
                <TableCell data-testid={`text-ticket-id-${ticket.id}`} className="font-mono text-xs">
                  <button
                    onClick={() => setTimeout(() => setEditingTicket(ticket), 0)}
                    className="text-[#FF9100] hover:underline cursor-pointer font-mono text-xs text-left"
                  >
                    {ticket.ticketNumber || `#${ticket.id}`}
                  </button>
                </TableCell>
                <TableCell className="w-7 px-1 py-1.5">
                  <div className="flex flex-col items-center gap-0.5">
                    <button
                      data-testid={`btn-flag-support-${ticket.id}`}
                      title={ticket.needsSupport ? "Needs support (click to clear)" : "Mark as needs support"}
                      onClick={(e) => { e.stopPropagation(); toggleNeedsSupport(ticket); }}
                      disabled={togglingSupport.has(ticket.id)}
                      className={`w-4 h-4 rounded-sm border flex items-center justify-center transition-colors ${ticket.needsSupport ? "bg-red-600 border-red-600 text-white" : "border-white/20 text-white/20 hover:border-red-500 hover:text-red-400"}`}
                    >
                      <Flag className="h-2.5 w-2.5" />
                    </button>
                    <button
                      data-testid={`btn-parts-needed-${ticket.id}`}
                      title={ticket.partsNeeded ? "Parts needed (click to clear)" : "Mark as parts needed"}
                      onClick={(e) => { e.stopPropagation(); togglePartsNeeded(ticket); }}
                      disabled={togglingParts.has(ticket.id)}
                      className={`w-4 h-4 rounded-sm border flex items-center justify-center transition-colors ${ticket.partsNeeded ? "bg-amber-500 border-amber-500 text-white" : "border-white/20 text-white/20 hover:border-amber-400 hover:text-amber-300"}`}
                    >
                      <Package className="h-2.5 w-2.5" />
                    </button>
                    <div
                      data-testid={`badge-new-ticket-${ticket.id}`}
                      title="Created within the last 48 hours"
                      className={`w-4 h-4 rounded-sm border flex items-center justify-center ${isNewTicket(ticket) ? "bg-blue-500 border-blue-500 text-white" : "border-white/20 text-white/20"}`}
                    >
                      <Sparkles className="h-2.5 w-2.5" />
                    </div>
                  </div>
                </TableCell>
                <TableCell data-testid={`text-ticket-title-${ticket.id}`} className="font-medium text-foreground">
                  <div className="flex items-center gap-1.5 flex-wrap">
                    {ticket.title}
                    {ticket.escalationLevel && ticket.escalationLevel !== "Standard" && ticket.escalationLevel !== "Normal" && (
                      <span
                        data-testid={`badge-escalation-${ticket.id}`}
                        className={`inline-flex items-center px-1.5 py-0 rounded-full border text-[10px] font-semibold ${
                          ticket.escalationLevel === "Critical" ? "bg-red-500/15 text-red-400 border-red-500/40" :
                          ticket.escalationLevel === "High" ? "bg-orange-500/15 text-orange-400 border-orange-500/40" :
                          "bg-amber-500/15 text-amber-400 border-amber-500/40"
                        }`}
                      >
                        {ticket.escalationLevel}
                      </span>
                    )}
                  </div>
                </TableCell>
                <TableCell data-testid={`text-ticket-customer-${ticket.id}`} className="max-w-[180px]">
                  <div className="text-sm text-muted-foreground truncate">{ticket.customerName || "—"}</div>
                  {(() => {
                    const creator = getTicketCreator(ticket);
                    return creator ? (
                      <div className="text-[11px] text-muted-foreground/55 truncate mt-0.5">{sn(creator)}</div>
                    ) : null;
                  })()}
                </TableCell>
                <TableCell data-testid={`text-ticket-system-${ticket.id}`} className="font-mono text-xs text-muted-foreground">
                  {ticket.systemId && ticket.csChannel ? (
                    <a
                      href={`https://app.slack.com/client/T019Y3V5LR4/${ticket.csChannel.replace(/^#/, "")}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-[#FF9100] hover:underline"
                      onClick={(e) => e.stopPropagation()}
                    >
                      {ticket.systemId}
                    </a>
                  ) : (
                    ticket.systemId || "—"
                  )}
                </TableCell>
                <TableCell data-testid={`text-ticket-priority-${ticket.id}`} className="p-0 pl-4">
                  <Select
                    value={ticket.priorityLabel || "__none__"}
                    disabled={changingPriority.has(ticket.id)}
                    onValueChange={(val) => {
                      handlePriorityChange(ticket, val === "__none__" ? null : val);
                    }}
                  >
                    <SelectTrigger
                      data-testid={`select-priority-${ticket.id}`}
                      className={`h-auto py-1 px-2 border-0 bg-transparent shadow-none focus:ring-0 text-sm font-medium w-auto min-w-[80px] max-w-[140px] ${
                        changingPriority.has(ticket.id) ? "opacity-50" :
                        ticket.priority === "high" ? "text-red-400" :
                        ticket.priority === "low" ? "text-gray-400" :
                        ticket.priorityLabel ? "text-foreground" :
                        "text-muted-foreground"
                      }`}
                    >
                      <SelectValue>
                        {ticket.priorityLabel ? shortenPriority(ticket.priorityLabel) : "—"}
                      </SelectValue>
                    </SelectTrigger>
                    <SelectContent>
                      <SelectItem value="__none__">— No priority</SelectItem>
                      {(options?.priorityLabels || []).map(p => (
                        <SelectItem key={p} value={p}>{p}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </TableCell>
                <TableCell data-testid={`text-ticket-hours-${ticket.id}`} className="text-right text-sm text-muted-foreground">
                  {ticket.status === "closed" ? (
                    <div className="flex flex-col items-end leading-tight">
                      <span className="text-[10px] font-medium text-muted-foreground/60 uppercase tracking-wide">Closed</span>
                      <span>{hoursOpen(ticket)}</span>
                    </div>
                  ) : (
                    hoursOpen(ticket)
                  )}
                </TableCell>
                <TableCell data-testid={`text-ticket-assignee-${ticket.id}`} className="text-sm text-muted-foreground">
                  <div className="flex flex-col leading-tight items-center">
                    <span>{sn(ticket.assigneeName)}</span>
                    <span className="text-[10px] text-muted-foreground/60">{timeSinceUpdate(ticket)}</span>
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
        </div>
      </div>

      <Dialog open={!!editingTicket} onOpenChange={(open) => !open && setEditingTicket(null)}>
        <DialogContent
          className="sm:max-w-[720px] max-h-[90vh] overflow-y-auto overflow-x-hidden overscroll-y-contain"
          onFocusOutside={(e) => e.preventDefault()}
        >
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              Edit {editingTicket?.ticketNumber || `Ticket #${editingTicket?.id}`}
              <button
                type="button"
                title="Copy link to this ticket"
                className="ml-1 text-muted-foreground hover:text-foreground transition-colors"
                onClick={() => {
                  const url = `${window.location.origin}/?ticket=${editingTicket?.id}`;
                  navigator.clipboard.writeText(url).then(() => {
                    setCopiedLink(true);
                    setTimeout(() => setCopiedLink(false), 2000);
                  });
                }}
              >
                {copiedLink
                  ? <CopyCheck className="h-3.5 w-3.5 text-green-500" />
                  : <Copy className="h-3.5 w-3.5" />}
              </button>
            </DialogTitle>
          </DialogHeader>
          {editingTicket && (
            <TicketFormErrorBoundary>
              <TicketForm 
                ticket={editingTicket} 
                onSuccess={() => setEditingTicket(null)}
                onCancel={() => setEditingTicket(null)}
              />
            </TicketFormErrorBoundary>
          )}
        </DialogContent>
      </Dialog>

      <CustomerDirectoryDialog
        open={directoryOpen}
        onOpenChange={setDirectoryOpen}
        customerContacts={options?.customerContacts ?? {}}
      />
    </>
  );
}
